version: "3.8"

services:
    db:
        image: postgres:16-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: bizantium
            POSTGRES_DB: taskIZI
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d taskIZI"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build: .
        restart: always
        ports:
            - "${PORT:-4000}:4000"
        env_file:
            - example.env
        environment:
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            # - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev

volumes:
    db_data:
    redis_data:
